# Generated by Django 6.0 on 2025-12-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.BigIntegerField(default=0)),
                ('doj', models.DateField()),
                ('mobile_number', models.BigIntegerField(default=0)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
